### ISSUE TITLE
Part 1: Lesson 4 - Common Responsive patterns

### ISSUE THREAD

**Issue by JeremieLitzler** [JeremieLitzler/mws-nanodegree-notes-2018#6]
# Patterns

## Layout Shifter: 
  - It highlights the order of the elements. 
  - Default of `order` is 0. 
  - Using negative values, we can put elements before the default-positionned elements.
  - Using postive values, we can put elements after the default-positionned elements.
## Column Drop
  - Small: all elements stacks
  - Medium: some elements are put beside each other
  - Large: Elements don't stack up but a margin is being added when the screen geets big the flex container remains centered.

```css
.item1 {
      background-color: red;
    }

    .item2 {
      background-color: blue;
    }

    .item3 {
      background-color: green;
    }

    .container {
      display: flex;
      flex-wrap: wrap;
    }

    .item {
      width: 100%;
      height: 200px;
    }

    @media screen and (min-width: 400px) {
      .item1 {
        width: 25%;
      }
      .item2 {
        width: 75%
      }
    }

    @media screen and (min-width: 600px) {
      .item1,
      .item3 {
        width: 25%;
      }
      .item2 {
        width: 50%
      }
    }
```

```html
<div class="container">
    <div class="item item1"></div>
    <div class="item item2"></div>
    <div class="item item3"></div>
</div>
```
## Off Canvas

- Generally used for a menu container
- We need that the elements take the full viewport width:

```css
html, body, main {
  width: 100%;
}
```
- We then need to style the navigation (**REMEMBER**: keep the width small or set width: 100% to prevent overflows!):

```css
nav {
  width: 300px; 
  height: 100%;
  position: absolute;
  transform: translate(-300px, 0);
  transition: transform 0.3s ease;
}
```

- We finally add the style to show the nav on click (javascript not included): 

```css
nav.open {
  transform: translate(0,0); //Reset the nav to show up!
}
```

#
