### ISSUE TITLE
Stage 1 - Lesson 5 - Optimizations

### ISSUE THREAD

**Issue by JeremieLitzler** [JeremieLitzler/mws-nanodegree-notes-2018#7]
## Font size and line length

- Use ~65 characterers per line (cpl) (between 45-90 cpl depending on the font).
- font-size should be 16px or 1em
- line-height should be 1.2em

## No more tables

- Use the following CSS under a certain screen width:

```css
@media screen and (max-width: 399px) {
  table,
  thead,
  tbody,
  th,
  td,
  tr {
    display: block;
  }
  thead tr {
    position: absolute;
    top: -9999px;
    left: -9999px;
  }
  td {
    position: relative;
    padding-left: 50%;
  }
  td:before {
    position: absolute;
    left: 6px;
    content: attr(data-th);
    font-weight: bold;
  }
}
```

## Responsive tables

- Start with wrapping the `table` element in a `div` element.
- Apply the following CSS to the wrapper: 

```css
.restaurant-hours__table {
  width: 100%;
  overflow-x: auto;
}
```
