### ISSUE TITLE
Stage 1 - Lesson 7 - Responsives Images

### ISSUE THREAD

**Issue by JeremieLitzler** [JeremieLitzler/mws-nanodegree-notes-2018#8]
# Using responsive images

Source: https://classroom.udacity.com/courses/ud882/

## Distributing equally images accross the viewport

```css
body {
      margin: 0;
    }
    img {
      float: left;
      margin-right: 10px;
      width: calc((100% - 20px)/3);
    }
    img:last-of-type {
     margin-right:0;   
    }
```

## Landscape vs Portrait

- For the height of images, use `vh` unit.
- For the width of images, use `vw` unit.

## Raster vs Vector

- Raster: should be used for content.
- Vector: should be used for icons or logos.
